namespace Semanticus.Engine
{
    /// <summary>
    /// The fabric-cicd scaffold templates emitted by <c>cicd_generate</c>: a parameter.yml + a CI workflow (GitHub
    /// Actions / Azure DevOps) + a deploy script that runs the REAL <c>fabric-cicd publish_all_items</c> in CI.
    /// PURE TEXT — the engine adds no Python dependency; it only authors the files CI will execute. Templates use a
    /// <c>__ENV__</c> placeholder (substituted with the chosen environment name) so the verbatim strings don't clash
    /// with the CI engines' own <c>${{ }}</c> / <c>$(...)</c> expression syntax.
    /// </summary>
    internal static class CicdTemplates
    {
        // The fabric-cicd parameter file: per-environment find/replace applied to the item definitions BEFORE publish.
        internal static string ParameterYml(string env, string workspaceId) => Sub(@"# Generated by Semanticus — fabric-cicd parameter file.
# Per-environment find/replace applied to the item definitions BEFORE publish.
# Dynamic tokens valid in replace_value: $workspace.$id (the target workspace GUID),
# $items.<ItemType>.<ItemName>.$id (a deployed item's GUID in the target workspace).
# Docs: https://microsoft.github.io/fabric-cicd/latest/how_to/parameterization/
find_replace:
  # Example — repoint a hard-coded dev workspace id to the target workspace at publish time
  # (replace the find_value below with a real id from your model to actually parameterize it):
  - find_value: ""__WSID__""  # dev workspace id
    replace_value:
      ""__ENV__"": ""$workspace.$id""
# key_value_replace:   # for JSON/YAML item files (e.g. Data Pipelines); .platform is excluded by design
#   - find_key: $.properties.someId
#     replace_value:
#       ""__ENV__"": ""replacement-value""
", env).Replace("__WSID__", workspaceId);

        // The deploy script the CI job runs — the official fabric-cicd FabricWorkspace + publish_all_items.
        internal static string DeployPy(string env) => Sub(@"# Generated by Semanticus — publishes this repo's Fabric items to a workspace using the official
# fabric-cicd package (https://aka.ms/fabric-cicd) + parameter.yml. Edit item_type_in_scope / the
# credential as needed. The Semanticus engine itself never runs this; CI does.
import os
from pathlib import Path
from azure.identity import DefaultAzureCredential
from fabric_cicd import FabricWorkspace, publish_all_items

repo = Path(__file__).resolve().parent.parent
workspace_id = os.environ[""FABRIC_WORKSPACE_ID""]
environment = os.environ.get(""FABRIC_ENVIRONMENT"", ""__ENV__"")

target = FabricWorkspace(
    workspace_id=workspace_id,
    environment=environment,
    repository_directory=str(repo),
    item_type_in_scope=[""SemanticModel"", ""Report""],
    token_credential=DefaultAzureCredential(),
)
publish_all_items(target)
", env);

        // GitHub Actions: pip install fabric-cicd, OIDC login, run the deploy script. ${{ }} is GitHub's own syntax.
        internal static string GithubWorkflow(string env) => Sub(@"name: Deploy Fabric semantic model
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install fabric-cicd
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Publish to Fabric
        run: python .deploy/deploy.py
        env:
          FABRIC_WORKSPACE_ID: ${{ vars.FABRIC_WORKSPACE_ID }}
          FABRIC_ENVIRONMENT: ""__ENV__""
", env);

        // Azure DevOps pipeline: same steps via an AzureCLI@2 task. $(...) is ADO's own variable syntax.
        internal static string AdoPipeline(string env) => Sub(@"trigger:
  branches:
    include: [ main ]
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
  - script: pip install fabric-cicd
    displayName: Install fabric-cicd
  - task: AzureCLI@2
    displayName: Publish to Fabric
    inputs:
      azureSubscription: '$(fabricServiceConnection)'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: python .deploy/deploy.py
    env:
      FABRIC_WORKSPACE_ID: $(FABRIC_WORKSPACE_ID)
      FABRIC_ENVIRONMENT: __ENV__
", env);

        private static string Sub(string template, string env) => template.Replace("__ENV__", env).Replace("\r\n", "\n");
    }
}
