using System.Threading.Tasks;
using Semanticus.Analysis;

namespace Semanticus.Engine
{
    /// <summary>
    /// The JSON-RPC method surface exposed to the VS Code extension over the named pipe. Method
    /// names are the wire names (camelCase). UI-initiated mutations are tagged origin = "human".
    /// Thin adapter over <see cref="IEngine"/> — identical operations are available to the MCP door.
    /// </summary>
    public sealed class EngineRpcTarget
    {
        private readonly IEngine _engine;
        public EngineRpcTarget(IEngine engine) => _engine = engine;

        public Task<OpenResult> open(string path) => _engine.OpenAsync(path);
        public Task<OpenResult> createModel(string name = null, int compatibilityLevel = 1604) => _engine.CreateModelAsync(name, compatibilityLevel);
        public Task<OpenResult> openLocal(string dataSource = null, string database = null) => _engine.OpenLocalAsync(dataSource, database);
        public Task<OpenResult> openLive(string endpoint, string database, string authMode = "azcli", string rawToken = null, string tenantId = null, bool forceReauth = false) => _engine.OpenLiveAsync(endpoint, database, authMode, rawToken, tenantId, forceReauth);
        public Task<DeployReport> deployLive(string endpoint, string database, string authMode = "serviceprincipal", string rawToken = null, string tenantId = null, bool commit = false, string origin = "human", string overrideReason = null) => _engine.DeployLiveAsync(endpoint, database, authMode, rawToken, tenantId, commit, origin, overrideReason);
        public Task<RefreshTypeInfo[]> listRefreshTypes() => _engine.ListRefreshTypesAsync();
        public Task<RefreshReport> refreshPartition(string partitionRef, string refreshType = "Full", string endpoint = null, string database = null, string authMode = null, string rawToken = null, string tenantId = null, bool commit = false, string origin = "human") => _engine.RefreshPartitionAsync(partitionRef, refreshType, endpoint, database, authMode, rawToken, tenantId, commit, origin);
        public Task<TreeNode[]> listTree(string parentRef) => _engine.ListTreeAsync(parentRef);
        public Task<ObjectInfo> getObject(string objRef) => _engine.GetObjectAsync(objRef);
        public Task<string> getDax(string objRef) => _engine.GetDaxAsync(objRef);
        public Task<SetResult> setDax(string objRef, string expression, string origin = "human") => _engine.SetDaxAsync(objRef, expression, origin);
        public Task<DaxLintResult> lintDax(string expression) => _engine.LintDaxAsync(expression);
        public Task<OptimizeMeasureResult> optimizeMeasure(string measureRef, string[] candidates, string[] verifyGroupBy = null, string[] verifyFilters = null, bool apply = true, string origin = "human") => _engine.OptimizeMeasureAsync(measureRef, candidates, verifyGroupBy, verifyFilters, apply, origin);
        public Task<ProbeResult> probeMeasure(string expr, string primaryAxis = null, ProbeScenario[] scenarios = null, bool includeDefaults = true, int rowCap = 5000) => _engine.ProbeMeasureAsync(expr, primaryAxis, scenarios, includeDefaults, rowCap);
        public Task<BaselineCaptureResult> captureBaseline(string objRef, string[] groupBy = null, string[] filters = null, bool includeDependents = true, int maxMeasures = 25, int rowCap = 2000, string label = null, string origin = "human") => _engine.CaptureBaselineAsync(objRef, groupBy, filters, includeDependents, maxMeasures, rowCap, label, origin);
        public Task<BaselineCompareResult> compareBaseline(string captureId = null, string label = null, string origin = "human") => _engine.CompareBaselineAsync(captureId, label, origin);
        public Task<BlameResult> blameValue(string measureRef, string context = null, string sinceCheckpoint = null, string origin = "human") => _engine.BlameValueAsync(measureRef, context, sinceCheckpoint, origin);
        public Task<ValueHistoryResult> listValueHistory(string measureRef, string context = null) => _engine.ListValueHistoryAsync(measureRef, context);
        public Task<ExplainDossier> explainValue(string measureRef, ExplainFilterContext context = null, bool decompose = true, string decomposeBy = null, int topK = 5, string origin = "human") => _engine.ExplainValueAsync(measureRef, context, decompose, decomposeBy, topK, origin);
        public Task<VerifiedEditsChain> listVerifiedEdits() => _engine.ListVerifiedEditsAsync();
        public Task<string> exportVerifiedEdits(string format = "md") => _engine.ExportVerifiedEditsAsync(format);
        public Task<TestSuiteRunResult> runTests(bool persist = false, string origin = "human") => _engine.RunTestSuiteAsync(persist, origin);
        public Task<TestSuiteInfo> listTests() => _engine.ListTestDefinitionsAsync();
        public Task<TestDefinition> saveTest(TestDefinition def, string origin = "human") => _engine.SaveTestDefinitionAsync(def, origin);
        public Task<bool> deleteTest(string id, string origin = "human") => _engine.DeleteTestDefinitionAsync(id, origin);
        public Task<TestHistoryInfo> listTestRuns(int last = 20) => _engine.ListTestRunsAsync(last);
        public Task<TestReportResult> exportTestReport() => _engine.ExportTestReportAsync();
        public Task<EvidenceLibrary> listEvidence() => _engine.ListEvidenceAsync();
        public Task<Semanticus.Engine.Evidence.EvidenceArtifact> getEvidence(string id) => _engine.GetEvidenceAsync(id);
        public Task<EvidenceSaveResult> saveEvidence(string source, string sourceId = null, string origin = "human") => _engine.SaveEvidenceAsync(source, sourceId, origin);
        public Task<ReconcileMappingReview> reviewReconcileMapping(ReconcileMappingRequest request, string origin = "human") => _engine.ReviewReconcileMappingAsync(request, origin);
        public Task<WorkflowInfo[]> listWorkflows() => _engine.ListWorkflowsAsync();
        public Task<WorkflowEnforcement> getWorkflowEnforcement() => _engine.GetWorkflowEnforcementAsync();
        public Task<WorkflowEnforcement> setWorkflowEnforcement(string mode = null, string origin = "human") => _engine.SetWorkflowEnforcementAsync(mode, origin);
        public Task<WorkflowInfo[]> setWorkflowEnabled(string name, bool enabled, string origin = "human") => _engine.SetWorkflowEnabledAsync(name, enabled, origin);
        public Task<WorkflowInfo[]> setWorkflowBinding(string op, string[] requireNames = null, string mode = null, string origin = "human") => _engine.SetWorkflowBindingAsync(op, requireNames, mode, origin);
        public Task<WorkflowInfo[]> setWorkflowActivation(string workflow, string when = null, string set = "on", string origin = "human") => _engine.SetWorkflowActivationAsync(workflow, when, set, origin);
        public Task<WorkflowPolicy> getWorkflowPolicy() => _engine.GetWorkflowPolicyAsync();
        public Task<WorkflowProfileInfo[]> listWorkflowProfiles() => _engine.ListWorkflowProfilesAsync();
        public Task<WorkflowProfileResult> activateWorkflowProfile(string name, string origin = "human") => _engine.ActivateWorkflowProfileAsync(name, origin);
        public Task<WorkflowDef> getWorkflow(string name) => _engine.GetWorkflowAsync(name);
        public Task<WorkflowRunView> startWorkflow(string name, string origin = "human") => _engine.StartWorkflowAsync(name, origin);
        public Task<WorkflowRunView> getWorkflowRun(string runId = null) => _engine.GetWorkflowRunAsync(runId);
        public Task<WorkflowRunView> submitWorkflowStep(string runId = null, string stepId = null, string answersJson = null, string origin = "human") => _engine.SubmitWorkflowStepAsync(runId, stepId, answersJson, origin);
        public Task<WorkflowRunView> skipWorkflowStep(string runId = null, string stepId = null, string reason = null, string origin = "human") => _engine.SkipWorkflowStepAsync(runId, stepId, reason, origin);
        public Task<WorkflowRunView> abortWorkflow(string runId = null, string reason = null, string origin = "human") => _engine.AbortWorkflowAsync(runId, reason, origin);
        public Task<Semanticus.Engine.Evidence.EvidenceArtifact> exportWorkflowEvidence(string runId = null) => _engine.ExportWorkflowEvidenceAsync(runId);
        public Task<WorkflowInfo[]> saveWorkflow(string name, string markdown, string origin = "human") => _engine.SaveWorkflowAsync(name, markdown, origin);
        public Task<WorkflowInfo[]> deleteWorkflow(string name, string origin = "human") => _engine.DeleteWorkflowAsync(name, origin);
        public Task<WorkflowTemplateInfo[]> listWorkflowTemplates() => _engine.ListWorkflowTemplatesAsync();
        public Task<WorkflowTemplate> getWorkflowTemplate(string name) => _engine.GetWorkflowTemplateAsync(name);
        public Task<WorkflowTemplateInfo[]> saveWorkflowTemplate(string name, string markdown, string origin = "human") => _engine.SaveWorkflowTemplateAsync(name, markdown, origin);
        public Task<WorkflowTemplateInfo[]> deleteWorkflowTemplate(string name, string origin = "human") => _engine.DeleteWorkflowTemplateAsync(name, origin);
        public Task<WorkflowInfo[]> instantiateWorkflowTemplate(string template, string name, string valuesJson = null, string origin = "human") => _engine.InstantiateWorkflowTemplateAsync(template, name, valuesJson, origin);
        public Task<OpInfo[]> getOpCatalog() => _engine.GetOpCatalogAsync();
        public Task<WorkflowCheckReport> checkWorkflow(string name) => _engine.CheckWorkflowAsync(name);
        public Task<WorkflowReplayReport> replayCheckWorkflow(string name) => _engine.ReplayCheckWorkflowAsync(name);
        public Task<DryRunReport> dryRunOp(string op, string argsJson = null) => _engine.DryRunOpAsync(op, argsJson);

        public Task<InsightRecord> addInsight(string text, string[] keys = null, string kind = "insight", string scope = "project", bool fingerprintScoped = false, string origin = "human") => _engine.AddInsightAsync(text, keys, kind, scope, fingerprintScoped, origin);
        public Task<InsightRecord> approveInsight(string id, string origin = "human") => _engine.ApproveInsightAsync(id, origin);
        public Task<InsightRecord> editInsight(string id, string text = null, string[] keys = null, string origin = "human") => _engine.EditInsightAsync(id, text, keys, origin);
        public Task<InsightRecord> upvoteInsight(string id, string origin = "human") => _engine.UpvoteInsightAsync(id, origin);
        public Task<InsightRecord> downvoteInsight(string id, string origin = "human") => _engine.DownvoteInsightAsync(id, origin);
        public Task<SetResult> deleteInsight(string id, string origin = "human") => _engine.DeleteInsightAsync(id, origin);
        public Task<PurgeResult> purgeKnowledge(string scope = "project", bool confirm = false, string origin = "human") => _engine.PurgeKnowledgeAsync(scope, confirm, origin);
        public Task<InsightListResult> listInsights(string scope = null, string status = null) => _engine.ListInsightsAsync(scope, status);
        public Task<RecallResult> recallExperience(string query = null, int maxResults = 12) => _engine.RecallExperienceAsync(query, maxResults);
        public Task<PrimerDocument> getPrimer() => _engine.GetPrimerAsync();
        public Task<PrimerDocument> setPrimer(string markdown, string origin = "human") => _engine.SetPrimerAsync(markdown, origin);
        public Task<PrimerSuggestionList> listPrimerSuggestions() => _engine.ListPrimerSuggestionsAsync();
        public Task<PrimerSuggestionDecision> acceptPrimerSuggestion(string id, string origin = "human") => _engine.AcceptPrimerSuggestionAsync(id, origin);
        public Task<PrimerSuggestionDecision> rejectPrimerSuggestion(string id, string origin = "human") => _engine.RejectPrimerSuggestionAsync(id, origin);
        public Task<ModelFingerprint> getModelFingerprint() => _engine.GetModelFingerprintAsync();
        public Task<InterviewListResult> listInterviewQuestions(string scope = null) => _engine.ListInterviewQuestionsAsync(scope);
        public Task<InterviewQuestion> addInterviewQuestion(string question, string tier, string query = null, string scalarExpr = null, string paraphraseExpr = null, string[] groupBy = null, string[] filters = null, string expectedValue = null, string expectedMatrixJson = null, bool expectRefusal = false, string fixRuleId = null, string seedSource = null, string scope = "project", string origin = "human") => _engine.AddInterviewQuestionAsync(question, tier, query, scalarExpr, paraphraseExpr, groupBy, filters, expectedValue, expectedMatrixJson, expectRefusal, fixRuleId, seedSource, scope, origin);
        public Task<InterviewRunResult> runInterview(string questionId = null, string inlineJson = null, bool abstained = false, string attemptDax = null, string origin = "human") => _engine.RunInterviewAsync(questionId, inlineJson, abstained, attemptDax, origin);
        public Task<SetResult> deleteInterviewQuestion(string id, string origin = "human") => _engine.DeleteInterviewQuestionAsync(id, origin);
        public Task<InterviewSeedResult> listInterviewSeeds(string source = null, string measure = null) => _engine.ListInterviewSeedsAsync(source, measure);
        public Task<SaveResult> save(string path, string format) => _engine.SaveAsync(path, format);
        public Task<SessionInfo> sessionInfo() => _engine.SessionInfoAsync();
        public Task<ConnectionContext> connectionContext() => _engine.ConnectionContextAsync();
        public Task<ModelConnectionRecord> rememberXmlaConnection(string endpoint, string database = null, string modelName = null, string authMode = "azcli", string origin = "human") => _engine.RememberXmlaConnectionAsync(endpoint, database, modelName, authMode, origin);
        public Task<WorkingCopyResult> prepareWorkingCopy(string connectionId, string parentFolder = null, bool commit = false, string queryConnectionId = null, string publishConnectionId = null, string origin = "human") => _engine.PrepareWorkingCopyAsync(connectionId, parentFolder, commit, queryConnectionId, publishConnectionId, origin);
        public Task<ConnectionContext> setPublishDestination(string connectionId, string origin = "human") => _engine.SetPublishDestinationAsync(connectionId, origin);
        public Task<Entitlement.EntitlementInfo> getEntitlement() => _engine.GetEntitlementAsync();
        public Task<VerifiedModeState> getVerifiedMode() => _engine.GetVerifiedModeAsync();
        public Task<VerifiedModeState> setVerifiedMode(bool on, string origin = "human") => _engine.SetVerifiedModeAsync(on, origin);
        public Task<ModelGraph> getModelGraph() => _engine.GetModelGraphAsync();
        public Task<LayoutData> getLayout() => _engine.GetLayoutAsync();
        public Task<SaveLayoutResult> saveLayout(LayoutNode[] tables, string origin = "human") => _engine.SaveLayoutAsync(tables, origin);
        public Task<VpaxExportResult> exportVpax(string path) => _engine.ExportVpaxAsync(path);
        public Task<SearchResult> searchModel(string query, int max = 100) => _engine.SearchModelAsync(query, max);
        public Task<SearchResult> searchModelEx(SearchOptions opts) => _engine.SearchModelAsync(opts);
        public Task<ReplaceResult> replaceInObject(ReplaceRequest req, string origin = "human") => _engine.ReplaceInObjectAsync(req, origin);
        public Task<MeasureRow[]> listMeasures() => _engine.ListMeasuresAsync();
        public Task<ColumnRow[]> listColumns() => _engine.ListColumnsAsync();
        public Task<ModelObjects> getModelObjects() => _engine.GetModelObjectsAsync();
        public Task<UndoState> undo(string origin = "human") => _engine.UndoAsync(origin);
        public Task<UndoState> redo(string origin = "human") => _engine.RedoAsync(origin);
        public Task publishActivity(ActivityEvent e) => _engine.PublishActivityAsync(e);
        public Task<HealthDelta> pullAgentHealth(string correlationId = null) => _engine.PullAgentHealthAsync(correlationId);

        public Task<BpaScorecard> bpaScan() => _engine.BpaScanAsync();
        public Task<SetResult> bpaFix(string ruleId, string objRef, string origin = "human") => _engine.BpaFixAsync(ruleId, objRef, origin);
        public Task<BpaFixAllResult> bpaFixAll(string origin = "human") => _engine.BpaFixAllAsync(origin);
        public Task<FixPrompt> bpaGetFixPrompt(string ruleId, string objRef) => _engine.BpaGetFixPromptAsync(ruleId, objRef);
        public Task<BpaRulesInfo> loadBpaRules(string source, bool replace = false, string origin = "human") => _engine.LoadBpaRulesAsync(source, replace, origin);
        public Task<BpaRulesInfo> resetBpaRules(string origin = "human") => _engine.ResetBpaRulesAsync(origin);
        public Task<ReadinessRulesInfo> loadReadinessRules(string source, bool replace = false, string origin = "human") => _engine.LoadReadinessRulesAsync(source, replace, origin);
        public Task<ReadinessRulesInfo> resetReadinessRules(string origin = "human") => _engine.ResetReadinessRulesAsync(origin);
        public Task<RuleValidationResult> validateRule(string kind, string rules) => _engine.ValidateRuleAsync(kind, rules);
        public Task<CustomRulesInfo> getCustomRules() => _engine.GetCustomRulesAsync();

        public Task<Scorecard> aiReadinessScan() => _engine.AiReadinessScanAsync();
        public Task<Scorecard> aiReadinessScanLive() => _engine.AiReadinessScanLiveAsync();
        public Task<SafeFixResult> applySafeFixes(string origin = "human") => _engine.ApplySafeFixesAsync(origin);
        public Task<SetResult> applyFix(string ruleId, string objRef, string origin = "human") => _engine.ApplyFixAsync(ruleId, objRef, origin);
        public Task<FixPrompt> getFixPrompt(string ruleId, string objRef) => _engine.GetFixPromptAsync(ruleId, objRef);
        public Task<GroundingBundle> getGrounding(string objRef) => _engine.GetGroundingAsync(objRef);
        public Task<SetResult> waiveFinding(string system, string ruleId, string objRef, string reason, string origin = "human") => _engine.WaiveFindingAsync(system, ruleId, objRef, reason, origin);
        public Task<SetResult> unwaiveFinding(string system, string ruleId, string objRef, string origin = "human") => _engine.UnwaiveFindingAsync(system, ruleId, objRef, origin);
        public Task<Semanticus.Analysis.WaiverRecord[]> listWaivers() => _engine.ListWaiversAsync();
        public Task<DaxValidation> validateDax(string expression) => _engine.ValidateDaxAsync(expression);
        public Task<SetResult> setDescription(string objRef, string text, string origin = "human") => _engine.SetDescriptionAsync(objRef, text, origin);
        // displayFolder is APPENDED (after origin) so the legacy 4-arg positional shape keeps binding — additive
        // RPC evolution, same pattern as duplicateObject's targetRef.
        public Task<string> createMeasure(string tableRef, string name, string expression, string origin = "human", string displayFolder = null) => _engine.CreateMeasureAsync(tableRef, name, expression, origin, displayFolder);
        public Task<TreeNode[]> listFunctions() => _engine.ListFunctionsAsync();
        public Task<string> createFunction(string name, string expression, string origin = "human") => _engine.CreateFunctionAsync(name, expression, origin);
        public Task<string> createTable(string name, string origin = "human") => _engine.CreateTableAsync(name, origin);
        public Task<string> createColumn(string tableRef, string name, string dataType = "String", string sourceColumn = null, string origin = "human") => _engine.CreateColumnAsync(tableRef, name, dataType, sourceColumn, origin);
        public Task<string> createDataSource(string name, string server = null, string database = null, string origin = "human") => _engine.CreateDataSourceAsync(name, server, database, origin);
        public Task<string> createNamedExpression(string name, string expression = null, string origin = "human") => _engine.CreateNamedExpressionAsync(name, expression, origin);
        public Task<PartitionInfo[]> listPartitions(string tableRef) => _engine.ListPartitionsAsync(tableRef);
        public Task<string> getPartitionM(string partitionRef) => _engine.GetPartitionMAsync(partitionRef);
        public Task<SetResult> setPartitionM(string partitionRef, string mExpression, string origin = "human") => _engine.SetPartitionMAsync(partitionRef, mExpression, origin);
        public Task<DocExpression[]> listNamedExpressions() => _engine.ListNamedExpressionsAsync();
        public Task<string> getNamedExpression(string name) => _engine.GetNamedExpressionAsync(name);
        public Task<SetResult> updateNamedExpression(string name, string expression, string origin = "human") => _engine.UpdateNamedExpressionAsync(name, expression, origin);
        public Task<string> createImportTable(string name, string mExpression = null, string origin = "human") => _engine.CreateImportTableAsync(name, mExpression, origin);
        public Task<string> createDirectLakeTable(string name, string entityName = null, string schemaName = null, string sourceName = null, string origin = "human") => _engine.CreateDirectLakeTableAsync(name, entityName, schemaName, sourceName, origin);
        public Task<string> createCalculatedTable(string name, string expression, string origin = "human") => _engine.CreateCalculatedTableAsync(name, expression, origin);
        public Task<string> createFieldParameter(string name, FieldParameterItem[] items, string origin = "human") => _engine.CreateFieldParameterAsync(name, items, origin);
        public Task<SetResult> setColumnDataType(string columnRef, string dataType, string origin = "human") => _engine.SetColumnDataTypeAsync(columnRef, dataType, origin);
        public Task<SourceSchema> getSourceSchema(string tableRef, string authMode = "azcli", string tenantId = null) => _engine.GetSourceSchemaAsync(tableRef, authMode, tenantId);
        public Task<SchemaDiff> diffSchema(string tableRef, SourceColumn[] sourceColumns = null, string authMode = "azcli", string tenantId = null) => _engine.DiffSchemaAsync(tableRef, sourceColumns, authMode, tenantId);
        public Task<ApplySchemaResult> applySchemaUpdate(string tableRef, SchemaUpdateItem[] items, string origin = "human") => _engine.ApplySchemaUpdateAsync(tableRef, items, origin);
        public Task<string> createCalculatedColumn(string tableRef, string name, string expression, string origin = "human") => _engine.CreateCalculatedColumnAsync(tableRef, name, expression, origin);
        public Task<string> createRelationship(string fromColumnRef, string toColumnRef, string crossFilter = null, bool? isActive = null, string origin = "human") => _engine.CreateRelationshipAsync(fromColumnRef, toColumnRef, crossFilter, isActive, origin);
        public Task<string> createHierarchy(string tableRef, string name, string[] levelColumns = null, string origin = "human") => _engine.CreateHierarchyAsync(tableRef, name, levelColumns, origin);
        public Task<string> createCalculationGroup(string name, string origin = "human") => _engine.CreateCalculationGroupAsync(name, origin);
        public Task<string> createCalculationItem(string calcGroupRef, string name, string expression, string origin = "human") => _engine.CreateCalculationItemAsync(calcGroupRef, name, expression, origin);
        public Task<CalcGroupInfo[]> listCalculationGroups() => _engine.ListCalculationGroupsAsync();
        public Task<string> createPerspective(string name, string origin = "human") => _engine.CreatePerspectiveAsync(name, origin);
        public Task<SetResult> setPerspectiveMember(string perspectiveRef, string objRef, bool include, string origin = "human") => _engine.SetPerspectiveMemberAsync(perspectiveRef, objRef, include, origin);
        public Task<PerspectiveInfo[]> getPerspectives() => _engine.GetPerspectivesAsync();
        public Task<SetResult> setCalcItemFormatString(string calcItemRef, string formatExpression, string origin = "human") => _engine.SetCalcItemFormatStringAsync(calcItemRef, formatExpression, origin);
        public Task<FormatTemplateInfo[]> listFormatTemplates(string category = null, string search = null) => _engine.ListFormatTemplatesAsync(category, search);
        public Task<SetResult> setMeasureFormatExpression(string objRef, string formatExpression, string origin = "human") => _engine.SetMeasureFormatExpressionAsync(objRef, formatExpression, origin);
        public Task<SetResult> setCalcGroupPrecedence(string calcGroupRef, int precedence, string origin = "human") => _engine.SetCalcGroupPrecedenceAsync(calcGroupRef, precedence, origin);
        public Task<DaxLibPackage[]> daxLibSearch(string text = null, int skip = 0, int take = 0) => _engine.DaxLibSearchAsync(text, skip, take);
        public Task<string[]> daxLibVersions(string id) => _engine.DaxLibVersionsAsync(id);
        public Task<DaxLibPackageDetail> daxLibPackageInfo(string id, string version = null) => _engine.DaxLibPackageInfoAsync(id, version);
        public Task<DaxLibInstallResult> daxLibInstall(string id, string version = null, bool replaceExisting = false, string origin = "human") => _engine.DaxLibInstallAsync(id, version, replaceExisting, origin);
        public Task<DaxLibInstalledRecord[]> daxLibListInstalled() => _engine.DaxLibListInstalledAsync();
        public Task<SetResult> daxLibUninstall(string id, string origin = "human") => _engine.DaxLibUninstallAsync(id, origin);
        public Task<SetResult> deleteObject(string objRef, string origin = "human") => _engine.DeleteObjectAsync(objRef, origin);
        // targetRef is APPENDED (after origin) so the legacy 3-arg positional shape (objRef, newName, origin)
        // keeps binding origin correctly from older extension bundles — additive RPC evolution, like searchModelEx.
        public Task<string> duplicateObject(string objRef, string newName = null, string origin = "human", string targetRef = null) => _engine.DuplicateObjectAsync(objRef, newName, targetRef, origin);
        public Task<ObjectProperty[]> getObjectProperties(string objRef) => _engine.GetObjectPropertiesAsync(objRef);
        public Task<SetResult> setObjectProperty(string objRef, string propertyName, string value, string origin = "human") => _engine.SetObjectPropertyAsync(objRef, propertyName, value, origin);
        // #140: the property-grid MULTI-select write — N objects, one atomic all-or-nothing undoable change.
        public Task<SetResult> setObjectProperties(string[] objRefs, string propertyName, string value, string origin = "human") => _engine.SetObjectPropertiesAsync(objRefs, propertyName, value, origin);
        public Task<SetResult> setDisplayFolder(string[] refs, string folder, string origin = "human") => _engine.SetDisplayFolderAsync(refs, folder, origin);
        public Task<FolderRenameResult> renameDisplayFolder(string tableRef, string fromPath, string toPath, string origin = "human") => _engine.RenameDisplayFolderAsync(tableRef, fromPath, toPath, origin);
        public Task<DependentInfo[]> getDependents(string objRef) => _engine.GetDependentsAsync(objRef);
        public Task<DependentInfo[]> getDependencies(string objRef) => _engine.GetDependenciesAsync(objRef);
        public Task<LineageResult> getLineage() => _engine.GetLineageAsync();
        public Task<ImpactResult> impactOf(string objRef) => _engine.ImpactOfAsync(objRef);
        public Task<Lineage.ImpactAssessmentResult> impactAssessment(Lineage.ImpactAssessmentRequest request) => _engine.ImpactAssessmentAsync(request);
        public Task<UnusedResult> unusedObjects() => _engine.UnusedObjectsAsync();
        public Task<ReportAnalysisResult> analyzeReports(string[] paths) => _engine.AnalyzeReportsAsync(paths);
        public Task<RemoveSafeReport> removeSafeObjects(string[] refs = null, string[] reportPaths = null, string origin = "human") => _engine.RemoveSafeObjectsAsync(refs, reportPaths, origin);
        public Task<CloudReport[]> listReports(string workspaceId, string authMode = "azcli", string tenantId = null) => _engine.ListReportsAsync(workspaceId, authMode, tenantId);
        public Task<ReportAnalysisResult> analyzeCloudReports(string workspaceId, string[] reportIds, bool consent = false, string authMode = "azcli", string tenantId = null) => _engine.AnalyzeCloudReportsAsync(workspaceId, reportIds, consent, authMode, tenantId);
        public Task<string> scriptObjects(string[] refs, string format) => _engine.ScriptObjectsAsync(refs, format);
        public Task<ApplyScriptResult> applyDaxScript(string script, string origin = "human") => _engine.ApplyDaxScriptAsync(script, origin);
        public Task<ApplyScriptResult> applyTmdlScript(string script, string origin = "human") => _engine.ApplyTmdlScriptAsync(script, origin);
        public Task<SetResult> setCompatibilityLevel(int level, string origin = "human") => _engine.SetCompatibilityLevelAsync(level, origin);
        public Task<RenameResult> renameObject(string objRef, string newName, string origin = "human") => _engine.RenameObjectAsync(objRef, newName, origin);
        public Task<SetResult> setColumnMetadata(string objRef, bool? isHidden, string summarizeBy, string dataCategory, string sortByColumn, string origin = "human") => _engine.SetColumnMetadataAsync(objRef, isHidden, summarizeBy, dataCategory, sortByColumn, origin);
        public Task<SetResult> setMeasureFormat(string objRef, string formatString, string origin = "human") => _engine.SetMeasureFormatAsync(objRef, formatString, origin);
        public Task<SetResult> markDateTable(string tableRef, string dateColumn, string origin = "human") => _engine.MarkDateTableAsync(tableRef, dateColumn, origin);
        public Task<RefreshPolicyInfo> getIncrementalRefreshPolicy(string tableRef) => _engine.GetIncrementalRefreshPolicyAsync(tableRef);
        public Task<SetResult> setIncrementalRefreshPolicy(string tableRef, string dateColumn, int? rollingWindowPeriods, string rollingWindowGranularity, int? incrementalPeriods, string incrementalGranularity, int? incrementalPeriodsOffset, string mode, string pollingExpression, bool autoWire = false, string origin = "human") => _engine.SetIncrementalRefreshPolicyAsync(tableRef, dateColumn, rollingWindowPeriods, rollingWindowGranularity, incrementalPeriods, incrementalGranularity, incrementalPeriodsOffset, mode, pollingExpression, autoWire, origin);
        public Task<SetResult> removeIncrementalRefreshPolicy(string tableRef, string origin = "human") => _engine.RemoveIncrementalRefreshPolicyAsync(tableRef, origin);
        public Task<SetResult> setRelationship(string relationshipName, string crossFilteringBehavior, bool? isActive, string origin = "human") => _engine.SetRelationshipAsync(relationshipName, crossFilteringBehavior, isActive, origin);
        public Task<SetResult> setRelationshipCardinality(string relationshipName, string fromCardinality, string toCardinality, string origin = "human") => _engine.SetRelationshipCardinalityAsync(relationshipName, fromCardinality, toCardinality, origin);
        public Task<ReadinessPlan> makeAiReady(string origin = "human", int maxQueue = 40) => _engine.MakeAiReadyAsync(origin, maxQueue);
        public Task<SetResult> enableQna(string culture = null, string origin = "human") => _engine.EnableQnaAsync(culture, origin);
        public Task<SetResult> setSynonyms(string objRef, string[] terms, string culture = null, string origin = "human") => _engine.SetSynonymsAsync(objRef, terms, culture, origin);
        public Task<SetInstructionsResult> setAiInstructions(string instructions, string culture = null, string origin = "human") => _engine.SetAiInstructionsAsync(instructions, culture, origin);
        public Task<AiInstructionsInfo> getAiInstructions(string culture = null) => _engine.GetAiInstructionsAsync(culture);
        public Task<SetResult> setAiDataSchema(string objRef, bool included, string culture = null, string origin = "human") => _engine.SetAiDataSchemaAsync(objRef, included, culture, origin);
        public Task<RoleInfo[]> listRoles() => _engine.ListRolesAsync();
        public Task<RoleInfo> createRole(string name, string modelPermission = null, string origin = "human") => _engine.CreateRoleAsync(name, modelPermission, origin);
        public Task<SetResult> deleteRole(string name, string origin = "human") => _engine.DeleteRoleAsync(name, origin);
        public Task<SetResult> setRolePermission(string name, string modelPermission, string origin = "human") => _engine.SetRolePermissionAsync(name, modelPermission, origin);
        public Task<SetTablePermissionResult> setTablePermission(string roleName, string tableRef, string filterDax, string origin = "human") => _engine.SetTablePermissionAsync(roleName, tableRef, filterDax, origin);
        public Task<SetResult> setRoleMember(string roleName, string memberName, bool add = true, string origin = "human") => _engine.SetRoleMemberAsync(roleName, memberName, add, origin);
        public Task<SetResult> setTableObjectPermission(string roleName, string tableRef, string permission, string origin = "human") => _engine.SetTableObjectPermissionAsync(roleName, tableRef, permission, origin);
        public Task<SetResult> setColumnObjectPermission(string roleName, string columnRef, string permission, string origin = "human") => _engine.SetColumnObjectPermissionAsync(roleName, columnRef, permission, origin);
        public Task<GenerateResult> generateDateTable(string tableName = "Date", string startExpr = null, string endExpr = null, bool markAsDate = true, string origin = "human") => _engine.GenerateDateTableAsync(tableName, startExpr, endExpr, markAsDate, origin);
        public Task<GenerateResult> generateTimeIntelligence(string baseMeasureRef, string dateColumn, string[] variants = null, string displayFolder = null, string origin = "human") => _engine.GenerateTimeIntelligenceAsync(baseMeasureRef, dateColumn, variants, displayFolder, origin);
        public Task<ModelSummary> getOrientation() => _engine.GetOrientationAsync();
        public Task<HarnessReportResult> harnessReport(int topN = 10) => _engine.HarnessReportAsync(topN);
        public Task<CalendarListResult> listCalendars(string tableRef = null) => _engine.ListCalendarsAsync(tableRef);
        public Task<CalendarResult> defineCalendar(string tableRef, string name, CalendarMappingSpec[] mappings, string description = null, string origin = "human") => _engine.DefineCalendarAsync(tableRef, name, mappings, description, origin);
        public Task<SetResult> deleteCalendar(string tableRef, string name, string origin = "human") => _engine.DeleteCalendarAsync(tableRef, name, origin);
        public Task<CalendarResult> tagCalendarColumn(string tableRef, string calendarName, string column, string timeUnit = null, bool associated = false, bool remove = false, string origin = "human") => _engine.TagCalendarColumnAsync(tableRef, calendarName, column, timeUnit, associated, remove, origin);
        public Task<CalendarResult> defineCalendarFromTemplate(string template, string tableName = null, string dateColumn = null, int fiscalStartMonth = 7, string startExpr = null, string endExpr = null, string calendarName = null, string origin = "human") => _engine.DefineCalendarFromTemplateAsync(template, tableName, dateColumn, fiscalStartMonth, startExpr, endExpr, calendarName, origin);
        public Task<ConnectionStatus> connectXmla(string endpoint, string database, string authMode = "azcli", string rawToken = null) => _engine.ConnectXmlaAsync(endpoint, database, authMode, rawToken);
        public Task<ConnectionStatus> connectLocal(string dataSource = null, string database = null) => _engine.ConnectLocalAsync(dataSource, database);
        public Task<LocalInstance[]> listLocalInstances() => _engine.ListLocalInstancesAsync();
        public Task<ConnectionStatus> connectionStatus() => _engine.ConnectionStatusAsync();
        public Task<ConnectionStatus> disconnect() => _engine.DisconnectAsync();
        public Task<ResultSet> runDax(string query, int maxRows = 10000, string origin = "human") => _engine.RunDaxAsync(query, maxRows, origin);
        public Task<ResultSet> runDmv(string query, int maxRows = 10000) => _engine.RunDmvAsync(query, maxRows);
        public Task<ResultSet> previewTable(string table, int topN = 200, string origin = "human") => _engine.PreviewTableAsync(table, topN, origin);
        public Task<ResultSet> pivotMeasure(string measureExpr, string[] rowFields, string colField, string[] filters, int maxRows = 100000, string origin = "human") => _engine.PivotMeasureAsync(measureExpr, rowFields, colField, filters, maxRows, origin);
        public Task<ReconcileRunResult> reconcileMeasure(ReconcileRequest request, string origin = "human") => _engine.ReconcileMeasureAsync(request, origin);
        public Task<VpaqReport> vertiPaqScan(int topN = 25) => _engine.VertiPaqScanAsync(topN);
        public Task<BenchmarkResult> benchmarkDax(string query, int runs = 5) => _engine.BenchmarkDaxAsync(query, runs);
        public Task<ServerTimings> profileDax(string query) => _engine.ProfileDaxAsync(query);
        public Task<EvalLogResult> evaluateAndLog(string query, int maxRows = 1000, string origin = "human") => _engine.EvaluateAndLogAsync(query, maxRows, origin);
        public Task<EquivalenceResult> verifyEquivalence(string exprA, string exprB, string[] groupBy, string[] filters, int maxRows = 100000) => _engine.VerifyEquivalenceAsync(exprA, exprB, groupBy, filters, maxRows);
        public Task<ClearCacheResult> clearCache(bool confirm = false) => _engine.ClearCacheAsync(confirm);
        public Task<ColdWarmBenchmark> benchmarkColdWarm(string query, int runs = 5, bool clearForCold = true, bool confirm = false) => _engine.BenchmarkColdWarmAsync(query, runs, clearForCold, confirm);
        public Task<QueryPlanResult> captureQueryPlan(string query) => _engine.CaptureQueryPlanAsync(query);

        public Task<ChangePlanView> proposePlan(string scope = null, bool includeAi = true, int maxAiItems = 40, string origin = "human") => _engine.ProposePlanAsync(scope, includeAi, maxAiItems, origin);
        public Task<ChangePlanView> proposeReplace(SearchOptions find, string replace = "", int maxItems = 500, string origin = "human") => _engine.ProposeReplaceAsync(find, replace, maxItems, origin);
        public Task<ChangePlanView> getPlan() => _engine.GetPlanAsync();
        public Task<ChangePlanView> addPlanItem(string objRef, string kind, string after = null, string title = null, string[] verifyGroupBy = null, string[] verifyFilters = null, string origin = "human") => _engine.AddPlanItemAsync(objRef, kind, after, title, verifyGroupBy, verifyFilters, origin);
        public Task<ChangePlanView> setPlanItem(string itemId, string after = null, bool? approved = null, string origin = "human") => _engine.SetPlanItemAsync(itemId, after, approved, origin);
        public Task<ApplyPlanReport> applyPlan(string[] approvedIds = null, string origin = "human", string[] overrideIds = null, string overrideReason = null) => _engine.ApplyPlanAsync(approvedIds, origin, overrideIds, overrideReason);
        public Task<ChangePlanView> clearPlan(string origin = "human") => _engine.ClearPlanAsync(origin);
        public Task<DocModelDto> getDocModel(int topN = 50) => _engine.GetDocModelAsync(topN);
        public Task<DocOutline> getDocOutline() => _engine.GetDocOutlineAsync();
        public Task<string> getDocSection(string objRef, string sectionKey) => _engine.GetDocSectionAsync(objRef, sectionKey);
        public Task<SetResult> setDocSection(string objRef, string sectionKey, string markdown, string origin = "human") => _engine.SetDocSectionAsync(objRef, sectionKey, markdown, origin);
        public Task<SpecView> getSpec() => _engine.GetSpecAsync();
        public Task<SpecView> setSpec(string specJson, string origin = "human") => _engine.SetSpecAsync(specJson, origin);
        public Task<SpecView> clearSpec(string origin = "human") => _engine.ClearSpecAsync(origin);
        public Task<SpecView> saveSpec(string path) => _engine.SaveSpecAsync(path);
        public Task<SpecView> loadSpec(string path, string origin = "human") => _engine.LoadSpecAsync(path, origin);
        public Task<SpecBuildReport> buildModelFromSpec(string origin = "human") => _engine.BuildModelFromSpecAsync(origin);
        public Task<SpecView> autogenerateSpecFromModel(string origin = "human") => _engine.AutogenerateSpecFromModelAsync(origin);
        public Task<SpecView> autogenerateSpecFromFabric(string server, string database, string authMode = "azcli", string storageMode = "import", string origin = "human", string tenantId = null) => _engine.AutogenerateSpecFromFabricAsync(server, database, authMode, storageMode, origin, tenantId);
        public Task<GitStatus> gitStatus() => _engine.GitStatusAsync();
        public Task<GitDiffResult> gitDiff(string path = null, bool staged = false) => _engine.GitDiffAsync(path, staged);
        public Task<GitLogEntry[]> gitLog(int max = 20) => _engine.GitLogAsync(max);
        public Task<GitCommitResult> gitCommit(string message, string[] files = null, bool commit = false, string origin = "human") => _engine.GitCommitAsync(message, files, commit, origin);
        public Task<HistoryCheckpointList> listHistoryCheckpoints(int max = 50) => _engine.ListHistoryCheckpointsAsync(max);
        public Task<HistoryCheckpointResult> createHistoryCheckpoint(string label = null, bool commit = false, string origin = "human") => _engine.CreateHistoryCheckpointAsync(label, commit, origin);
        public Task<HistoryRestoreResult> restoreHistoryCheckpoint(string hash, bool restore = false, string origin = "human") => _engine.RestoreHistoryCheckpointAsync(hash, restore, origin);
        public Task<GitActionResult> gitBranch(string name = null, bool create = false, bool checkout = false, string origin = "human") => _engine.GitBranchAsync(name, create, checkout, origin);
        public Task<GitActionResult> gitCheckout(string gitRef, string origin = "human") => _engine.GitCheckoutAsync(gitRef, origin);
        public Task<GitActionResult> gitPull(string origin = "human") => _engine.GitPullAsync(origin);
        public Task<GitActionResult> gitPush(string remote = null, string branch = null, bool confirm = false, string origin = "human") => _engine.GitPushAsync(remote, branch, confirm, origin);
        public Task<GitActionResult> gitClone(string url, string directory, string origin = "human") => _engine.GitCloneAsync(url, directory, origin);
        // The RPC door IS the human door (the Studio webview); a compare against a not-signed-in workspace target may
        // therefore open an interactive sign-in. Origin defaults to "human" here for exactly that reason.
        public Task<ModelDiff> compareModels(ModelRef left, ModelRef right, bool includeEqual = false, string origin = "human") => _engine.CompareModelsAsync(left, right, includeEqual, origin);
        public Task<ApplyDiffResult> applyDiff(ModelRef left, ModelRef right, string[] selectedRefs = null, bool commit = false, string origin = "human", string overrideReason = null) => _engine.ApplyDiffAsync(left, right, selectedRefs, commit, origin, overrideReason);
        public Task<CherryPickResult> cherryPick(ModelRef source, string[] refs, bool includeDependencies = true, bool commit = false, string origin = "human") => _engine.CherryPickAsync(source, refs, includeDependencies, commit, origin);
        // The RPC door IS the human door (the Studio Reference Model picker, which offers an XMLA/workspace source), so
        // a browse of a not-signed-in workspace may open the interactive sign-in — origin defaults to "human" here.
        public Task<TreeNode[]> listReferenceTree(ModelRef reference, string origin = "human") => _engine.ListReferenceTreeAsync(reference, origin);
        public Task<DeployGate> deployGate(ModelRef compareTarget = null) => _engine.DeployGateAsync(compareTarget);
        public Task<ModelConnectionRecord[]> listConnections() => _engine.ListConnectionsAsync();
        public Task<ModelConnectionRecord> labelConnection(string id, string label, string origin = "human") => _engine.LabelConnectionAsync(id, label, origin);
        public Task<ModelConnectionRecord> setConnectionWorkingFolder(string id, string folder) => _engine.SetConnectionWorkingFolderAsync(id, folder);
        public Task<bool> forgetConnection(string id, string origin = "human") => _engine.ForgetConnectionAsync(id, origin);
        // Agent policy + approvals. The RPC door IS the human/UI door: mutations default origin "human", which is what
        // lets the human set the policy and approve actions the agent cannot.
        public Task<AgentPolicy> getAgentPolicy() => _engine.GetAgentPolicyAsync();
        public Task<AgentPolicy> setAgentPolicyPreset(string preset, string origin = "human") => _engine.SetAgentPolicyPresetAsync(preset, origin);
        public Task<AgentPolicy> setAgentPolicyCell(string capability, string label, string action, string origin = "human") => _engine.SetAgentPolicyCellAsync(capability, label, action, origin);
        public Task<AgentPolicy> setAgentPolicyEnabled(bool enabled, string origin = "human") => _engine.SetAgentPolicyEnabledAsync(enabled, origin);
        public Task<ApprovalRecord[]> listPendingApprovals() => _engine.ListPendingApprovalsAsync();
        public Task<ApprovalRecord> approveAgentAction(string id, string origin = "human") => _engine.ApproveAgentActionAsync(id, origin);
        public Task<bool> denyAgentAction(string id, string origin = "human") => _engine.DenyAgentActionAsync(id, origin);
        public Task<RestorePointRecord[]> listRestorePoints(string endpoint = null, string database = null) => _engine.ListRestorePointsAsync(endpoint, database);
        public Task<RollbackResult> rollbackPush(string restorePointId, bool commit = false, string authMode = null, string origin = "human") => _engine.RollbackPushAsync(restorePointId, commit, authMode, origin);
        public Task<RestorePointPurgeResult> purgeRestorePoints(string id = null, int? olderThanDays = null,
            bool confirm = false, string confirmToken = null, string origin = "human") =>
            _engine.PurgeRestorePointsAsync(id, olderThanDays, confirm, confirmToken, origin);
        public Task<FabricWorkspace[]> listWorkspaces(string authMode = "azcli", string tenantId = null) => _engine.ListWorkspacesAsync(authMode, tenantId);
        public Task<DeploymentPipeline[]> listDeploymentPipelines(string authMode = "azcli", string tenantId = null) => _engine.ListDeploymentPipelinesAsync(authMode, tenantId);
        public Task<PipelineStage[]> getPipelineStages(string pipelineId, string authMode = "azcli", string tenantId = null) => _engine.GetPipelineStagesAsync(pipelineId, authMode, tenantId);
        public Task<StageItem[]> getStageItems(string pipelineId, string stageId, string authMode = "azcli", string tenantId = null) => _engine.GetStageItemsAsync(pipelineId, stageId, authMode, tenantId);
        public Task<DeployPreview> previewDeploy(string pipelineId, string sourceStageId, string targetStageId, string authMode = "azcli", string tenantId = null) => _engine.PreviewDeployAsync(pipelineId, sourceStageId, targetStageId, authMode, tenantId);
        public Task<DeployStageReport> deployStage(string pipelineId, string sourceStageId, string targetStageId, string[] items = null, string note = null, bool commit = false, string confirmToken = null, bool forceOverride = false, string authMode = "azcli", string tenantId = null, string origin = "human", string overrideReason = null) => _engine.DeployStageAsync(pipelineId, sourceStageId, targetStageId, items, note, commit, confirmToken, forceOverride, authMode, tenantId, origin, overrideReason);
        public Task<DeploymentHistoryEntry[]> deploymentHistory(string pipelineId, string authMode = "azcli", string tenantId = null) => _engine.DeploymentHistoryAsync(pipelineId, authMode, tenantId);
        public Task<FabricGitConnection> fabricGitConnection(string workspaceId, string authMode = "azcli", string tenantId = null) => _engine.FabricGitConnectionAsync(workspaceId, authMode, tenantId);
        public Task<FabricGitStatus> fabricGitStatus(string workspaceId, string authMode = "azcli", string tenantId = null) => _engine.FabricGitStatusAsync(workspaceId, authMode, tenantId);
        public Task<FabricGitResult> fabricGitCommit(string workspaceId, string comment = null, string[] items = null, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.FabricGitCommitAsync(workspaceId, comment, items, commit, authMode, tenantId, origin);
        public Task<FabricGitResult> fabricGitUpdate(string workspaceId, string conflictPolicy = "PreferRemote", bool allowOverride = false, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.FabricGitUpdateAsync(workspaceId, conflictPolicy, allowOverride, commit, authMode, tenantId, origin);
        public Task<FabricGitResult> fabricGitConnect(string workspaceId, string provider, string organization, string project = null, string repository = null, string branch = "main", string directory = null, string connectionId = null, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.FabricGitConnectAsync(workspaceId, provider, organization, project, repository, branch, directory, connectionId, commit, authMode, tenantId, origin);
        public Task<FabricGitResult> fabricGitDisconnect(string workspaceId, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.FabricGitDisconnectAsync(workspaceId, commit, authMode, tenantId, origin);
        public Task<CicdPublishResult> cicdPublish(string workspaceId, string itemId, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.CicdPublishAsync(workspaceId, itemId, commit, authMode, tenantId, origin);
        public Task<CicdScaffold> cicdGenerate(string target = "github", string workspaceId = null, string environment = "PROD", bool write = false) => _engine.CicdGenerateAsync(target, workspaceId, environment, write);
        public Task<DataAgentList> listDataAgents(string workspaceId, string authMode = "azcli", string tenantId = null) => _engine.ListDataAgentsAsync(workspaceId, authMode, tenantId);
        public Task<DataAgentDetail> getDataAgent(string workspaceId, string agentId, string authMode = "azcli", string tenantId = null) => _engine.GetDataAgentAsync(workspaceId, agentId, authMode, tenantId);
        public Task<DataAgentConfig> generateDataAgentConfig(int maxColumnsPerTable = 200) => _engine.GenerateDataAgentConfigFromModelAsync(maxColumnsPerTable);
        public Task<DataAgentWriteReport> createDataAgent(string workspaceId, string name, string aiInstructions = null, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.CreateDataAgentAsync(workspaceId, name, aiInstructions, commit, authMode, tenantId, origin);
        public Task<DataAgentWriteReport> updateDataAgent(string workspaceId, string agentId, string aiInstructions = null, string datasourceFolder = null, string datasourceJson = null, string fewshotsJson = null, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.UpdateDataAgentAsync(workspaceId, agentId, aiInstructions, datasourceFolder, datasourceJson, fewshotsJson, commit, authMode, tenantId, origin);
        public Task<DataAgentWriteReport> publishDataAgent(string workspaceId, string agentId, string description = null, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.PublishDataAgentAsync(workspaceId, agentId, description, commit, authMode, tenantId, origin);
        public Task<DataAgentWriteReport> deleteDataAgent(string workspaceId, string agentId, bool commit = false, string authMode = "azcli", string tenantId = null, string origin = "human") => _engine.DeleteDataAgentAsync(workspaceId, agentId, commit, authMode, tenantId, origin);
    }
}
